import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { Container, Box, Typography, Button, TextField } from '@mui/material';
import { makeStyles } from '@material-ui/core/styles';
import image from '../public/images/logo.png';
import Image from 'next/image';
import { styled } from '@mui/system';

import {
  CalendarMonthOutlined,
  MessageOutlined,
  ContentPasteSearchOutlined,
  AccountCircleOutlined,
  GroupsOutlined,
  AssignmentOutlined,
  Settings,
  Logout,
  Add,
  Search,
  Link,
  PersonOutlined,
  AddAlertOutlined,
} from '@mui/icons-material';

// const url = `https://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=a4850c5e5b7c9f5832a284d1bd12deea`;

// async function getLocation() {
//   try {
//     const response = await axios.get(url);
//     console.log(response.data);
//     return response.data;
//   } catch (error) {
//     console.error(error);
//   }
// }
const isActive = true;

const Aside = styled('aside')({});
const Input = styled('input')({});
const useStyles = makeStyles({
  MainBox: {
    display: 'flex',
    width: '216px',
    height: '48px',
    flexDirection: 'row',
    alignItems: 'center',
    p: '12px',
    gap: '12px',
    borderRadius: '6px',
    flex: 'none',
    order: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  MainBoxIsActive: {
    background: '#E9F4F5',
    display: 'flex',
    width: '216px',
    height: '48px',
    flexDirection: 'row',
    alignItems: 'center',
    p: '12px',
    gap: '12px',
    borderRadius: '6px',
    flex: 'none',
    order: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  TypographyBox: {
    width: '80%',
    height: '21px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#4CA7A8',
    flex: 'none',
    order: 1,
    flexGrow: 0,
  },
  sideBarIcon: {
    width: '15px',
    height: '15px',
    margin: '2px',
  },
  sideBarIconRotate: {
    transform: 'rotate(180deg)',
    width: '15px',
    height: '15px',
    margin: '2px',
  },
  boxProvider: {
    position: 'absolute',
    width: '218px',
    height: '71px',
    left: '23px',
    top: '53px',
    backgroundColor: '#355072',
  },
  TypographyBoxUnic: {
    marginLeft: '-7px',
    marginBottom: '10px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#AEAEAE',
  },
  labelIndex: {
    position: 'absolute',
    top: '55px',
    marginLeft: '20px',
    fontSize: '16px',
  },
  TypographyHeader: {
    width: '86px',
    height: '34px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '24px',
    lineHeight: '140%',
    color: '#0F1527',
    flex: 'none',
    order: 0,
    flexGrow: 0,
  },
  TypographyText: {
    width: '229px',
    height: '21px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#AEAEAE',
    flex: 'none',
    order: 1,
    flexGrow: 0,
    marginRight: '80px',
  },
  BoxButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 24px',
    gap: '8px',
    width: '144px',
    height: '38px',
    background: '#4CA7A8',
    borderRadius: '6px',
    flex: 'none',
    order: 0,
    flexGrow: 0,
    marginTop: '10px',
  },
  ButtonAdd: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    padding: '10px 24px',
    alignItems: 'center',
    width: '144px',
    height: '38px',
    background: '#4CA7A8',
    borderRadius: '6px',
    flex: 'none',
    order: 0,
    flexGrow: 0,
    border: 0,
    cursor: 'pointer',
  },
  ButtonAddText: {
    width: '96px',
    p: '2px',
    height: '18px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '130%',
    color: '#FFFFFF',
    flex: 'none',
    order: 0,
    flexGrow: 0,
  },
  BoxSearch: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: '16px',
    gap: '8px',
    width: '460px',
    height: '56px',
    background: '#FAFAFA',
    borderRadius: '12px',
    flex: 'none',
    // order: 1,
    flexGrow: 0,
    margin: '0px 10px',
  },
});

const Home: NextPage = () => {
  // const { data, isError, isLoading } = useQuery(['location'], () =>
  //   getLocation(),
  // );
  const classes = useStyles('active');
  return (
    <Box className={styles.container}>
      <Head>
        <title>Fasters</title>
        <meta
          name="og:title"
          property="og:title"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="vercel" href="" />
      </Head>
      {/* {isLoading ? 'Loading...' : null}
      {isError ? 'Error' : null} */}
      <nav className={styles.nav}>
        <Box sx={{ m: 4.7, display: 'flex' }}>
          <Box>
            <Typography className={classes.TypographyHeader}>
              Janeiro
            </Typography>
            <Typography className={classes.TypographyText}>
              Quinta-feira - 4 de Jan 2022
            </Typography>
          </Box>
          <Box className={classes.BoxButton}>
            <button className={classes.ButtonAdd}>
              <Typography sx={{ color: 'white', padding: '5px' }}>+</Typography>
              <Typography
                variant="subtitle1"
                sx={{
                  fontFamily: 'DM Sans',
                  fontStyle: 'normal',
                  fontWeight: 400,
                  fontSize: '14px',
                  lineHeight: '130%',
                  width: '144px',
                }}
              >
                Create Event
              </Typography>
            </button>
          </Box>
          <Box className={classes.BoxSearch}>
            <Search sx={{ color: '#AEAEAE' }} />
            <input type="text" placeholder="Search Task, event, calendar" />
          </Box>

          <Button
            sx={{
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '16px',
              gap: '8px',
              width: '56px',
              height: '56px',
              background: '#FAFAFA',
              borderRadius: '12px',
              flex: 'none',
              flexGrow: 0,
              marginRight: '10px',
            }}
            startIcon={
              <AddAlertOutlined sx={{ color: '#aeaeae', marginLeft: '5px' }} />
            }
          />
          <Button
            sx={{
              flexDirection: 'row',
              alignItems: 'flex-start',
              padding: '16px',
              gap: '8px',
              width: '56px',
              height: '56px',
              background: '#FAFAFA',
              borderRadius: '12px',
              flex: 'none',
              flexGrow: 0,
            }}
            startIcon={
              <PersonOutlined sx={{ color: '#aeaeae', marginLeft: '5px' }} />
            }
          />
        </Box>
      </nav>

      <Aside className={styles.sidebar}>
        <Container sx={{ m: '3rem' }}>
          <Box className={classes.boxProvider}>
            <Box sx={{ p: 2 }}>
              <Image alt="Vercel logo" src={image} width={205} height={41} />
            </Box>
            <Box className={classes.MainBoxIsActive}>
              <CalendarMonthOutlined
                className={classes.sideBarIcon}
                sx={{ fill: '#355072' }}
              />
              <Typography className={classes.TypographyBox}>Agenda</Typography>
            </Box>
            <Box className={classes.MainBox}>
              <MessageOutlined className={classes.sideBarIcon} />
              <Typography className={classes.TypographyBox}>
                Mensagens
              </Typography>
            </Box>
            <Box className={classes.MainBox}>
              <ContentPasteSearchOutlined className={classes.sideBarIcon} />
              <Typography className={classes.TypographyBox}>
                Relatórios
              </Typography>
            </Box>
            <Typography className={classes.TypographyBoxUnic}>
              My account
            </Typography>
            <Box className={classes.MainBox}>
              <AccountCircleOutlined className={classes.sideBarIcon} />
              <Typography className={classes.TypographyBox}>
                Meus Eventos
              </Typography>
            </Box>
            <Box className={classes.MainBox}>
              <GroupsOutlined className={classes.sideBarIcon} />
              <Typography className={classes.TypographyBox}>
                Meu Time
              </Typography>
            </Box>
            <Box className={classes.MainBox} sx={{ mb: '5rem' }}>
              <AssignmentOutlined className={classes.sideBarIcon} />
              <Typography className={classes.TypographyBox}>
                Minhas Atividades
              </Typography>
            </Box>
            <Typography className={classes.TypographyBoxUnic}>
              System
            </Typography>
            <Box className={classes.MainBox}>
              <Settings className={classes.sideBarIcon} />
              <Typography className={classes.TypographyBox}>
                Configurações
              </Typography>
            </Box>
            <Box className={classes.MainBoxIsActive}>
              <Logout
                className={classes.sideBarIconRotate}
                sx={{ fill: '#355072' }}
              />
              <Typography className={classes.TypographyBox}>Sair</Typography>
            </Box>
          </Box>
        </Container>

        {/* {data ? <span>{data.main.temp}</span> : 'calma'} */}
      </Aside>

      <main className={styles.main}>
        <h1>main</h1>
      </main>
    </Box>
  );
};

export default Home;
