import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="og:title" property="og:title" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="vercel" href="https://yourwebsite.com/"/>
      </Head>

      <main className={styles.main}>
        <h1>main</h1>
      </main>

      <footer className={styles.footer}>
        <h1>footer</h1>
      </footer>
    </div>
  )
}

export default Home
